# 目标|MIUI 原始 lowerdir。先卸载只读 MIUI Overlay，再用相同 lowerdir 加上持久化 upper/work 重建。
/product/overlay|/mnt/vendor/mi_ext/product/overlay/:/product/overlay
/product/app|/mnt/vendor/mi_ext/product/app/:/product/app
/product/priv-app|/mnt/vendor/mi_ext/product/priv-app/:/product/priv-app
/product/lib|/mnt/vendor/mi_ext/product/lib/:/product/lib
/product/lib64|/mnt/vendor/mi_ext/product/lib64/:/product/lib64
/product/framework|/mnt/vendor/mi_ext/product/framework/:/product/framework
/product/media|/mnt/vendor/mi_ext/product/media/:/product/media
/product/opcust|/mnt/vendor/mi_ext/product/opcust/:/product/opcust
/product/data-app|/mnt/vendor/mi_ext/product/data-app/:/product/data-app
/product/usr|/mnt/vendor/mi_ext/product/usr:/product/usr
/system/app|/mnt/vendor/mi_ext/system/app/:/product/pangu/system/app/:/system/app
/system/priv-app|/mnt/vendor/mi_ext/system/priv-app/:/product/pangu/system/priv-app/:/system/priv-app
/system/framework|/product/pangu/system/framework/:/system/framework
/product/etc/sysconfig|/mnt/vendor/mi_ext/product/etc/sysconfig/:/product/etc/sysconfig
/product/etc/permissions|/mnt/vendor/mi_ext/product/etc/permissions/:/product/etc/permissions
/product/etc/precust_theme|/mnt/vendor/mi_ext/product/etc/precust_theme:/product/etc/precust_theme
/product/etc/preferred-apps|/mnt/vendor/mi_ext/product/etc/preferred-apps:/product/etc/preferred-apps
/product/etc/security|/mnt/vendor/mi_ext/product/etc/security:/product/etc/security
/system/etc/sysconfig|/mnt/vendor/mi_ext/system/etc/sysconfig/:/system/etc/sysconfig
/system/etc/permissions|/mnt/vendor/mi_ext/system/etc/permissions/:/product/pangu/system/etc/permissions/:/system/etc/permissions
/system_ext/etc/permissions|/mnt/vendor/mi_ext/system_ext/etc/permissions:/system_ext/etc/permissions
/vendor/etc/camera|/odm/etc/camera/:/vendor/etc/camera
/vendor/lib/rfsa/adsp|/odm/mount/camera/lib/rfsa/adsp/:/vendor/lib/rfsa/adsp

